### PR TITLE
changed the vETh2 logo

### PR DESCRIPTION
**Pull request by sharedStake-main**

### CODE REVIEW

**Review by hammeiam — APPROVED** [review]
Thanks for the PR!

**Comment by hammeiam** [comment]
Hi @sharedStake-main could you sign your commit with a gpg key? Here are the basic instructions https://dev.to/shostarsson/how-to-use-pgp-to-sign-your-commits-on-github-gitlab-bitbucket-3dae

**Comment by sharedStake-main** [comment]
Hi @hammeiam its signed and also updated with a proper image now :slightly_smiling_face:

**Review by alphastorm — CHANGES_REQUESTED** [review]
hey @sharedStake-main the image is a different width/height than before so it appears much larger than the other icons in the UI:

Screen Shot 2021-05-12 at 9 57 31 AM

you can access the preview here:

changed_the_vETh2_logo_by_sharedStake-main_·_Pull_Request__453_·_saddle-finance_saddle-frontend

once this is fixed the PR should be ready to land!

**Comment by alphastorm** [comment]
Replaced by https://github.com/saddle-finance/saddle-frontend/pull/495

**Pull request closed without merging**
