### PR TITLE
Disable ramp A value and end data when date value is zero

### PR DESCRIPTION
**Pull request by nkrulikovsky**
## Description

For pool that have never changed their A parameter, ramping end date value is zero(Big number). In this case, we don't need to display this value

image

image

### CODE REVIEW

**Review by hammeiam — APPROVED** [review]
Will this also address the future A value being incorrectly shown as 10,000? Less importantly, do we want to display futureATimes from the past?

**Review by nguyenaiden — COMMENTED** [review]
Could you add a screen capture in the PR description?

**Review by hammeiam — APPROVED** [review]
Thanks for the precision update!

**Comment by nkrulikovsky** [comment]
@nguyenaiden 
Added screenshot

**Pull request merged**
